# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stardazed
email: arthur@stardazed.club
description: > # this means to ignore newlines until "baseurl:"
  Stardazed TX is an exciting, in-development web 3D game library
  designed for efficiency, small footprint and easy prototyping.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stardazed.club" # the base hostname & protocol for your site
twitter_username: clubstardazed
github_username:  stardazed

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
   - jekyll-paginate
